/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import java.util.Date;
import controlador.Controlador;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author violi
 */
public class DialogInsercion extends javax.swing.JDialog {

    /**
     * 
     * @param parent
     * @param modal
     * @param controlador 
     */
    public DialogInsercion(DialogTiendas parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        initComponents();
        this.controlador=controlador;
        this.padre=parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInsert = new javax.swing.JPanel();
        pnlInsertDcha = new javax.swing.JPanel();
        pnlInsertIzqda = new javax.swing.JPanel();
        pnlInsertCentro = new javax.swing.JPanel();
        lblInsertTitulo = new javax.swing.JLabel();
        lblInsertIndicaciones = new javax.swing.JLabel();
        lblInsertNombre = new javax.swing.JLabel();
        lblInsertLocalidad = new javax.swing.JLabel();
        lblInsertProvincia = new javax.swing.JLabel();
        lblInsertCodPost = new javax.swing.JLabel();
        lblInsertSuperficie = new javax.swing.JLabel();
        lblInsertFechApertura = new javax.swing.JLabel();
        txtInsertNombre = new javax.swing.JTextField();
        txtInsertLocalidad = new javax.swing.JTextField();
        cmbInsertProvincia = new javax.swing.JComboBox<>();
        txtInsertCodPost = new javax.swing.JTextField();
        txtInsertSuperficie = new javax.swing.JTextField();
        spnInsertFechApertura = new javax.swing.JSpinner();
        btnInsertBorrar = new javax.swing.JButton();
        btnInsertGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlInsert.setLayout(new java.awt.BorderLayout());

        pnlInsertDcha.setBackground(new java.awt.Color(0, 153, 51));
        pnlInsertDcha.setPreferredSize(new java.awt.Dimension(50, 300));

        javax.swing.GroupLayout pnlInsertDchaLayout = new javax.swing.GroupLayout(pnlInsertDcha);
        pnlInsertDcha.setLayout(pnlInsertDchaLayout);
        pnlInsertDchaLayout.setHorizontalGroup(
            pnlInsertDchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlInsertDchaLayout.setVerticalGroup(
            pnlInsertDchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pnlInsert.add(pnlInsertDcha, java.awt.BorderLayout.EAST);

        pnlInsertIzqda.setBackground(new java.awt.Color(255, 255, 204));
        pnlInsertIzqda.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout pnlInsertIzqdaLayout = new javax.swing.GroupLayout(pnlInsertIzqda);
        pnlInsertIzqda.setLayout(pnlInsertIzqdaLayout);
        pnlInsertIzqdaLayout.setHorizontalGroup(
            pnlInsertIzqdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlInsertIzqdaLayout.setVerticalGroup(
            pnlInsertIzqdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlInsert.add(pnlInsertIzqda, java.awt.BorderLayout.WEST);

        pnlInsertCentro.setBackground(new java.awt.Color(255, 255, 255));

        lblInsertTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInsertTitulo.setText("Añadir Tienda");

        lblInsertIndicaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInsertIndicaciones.setText("<html><p>Por favor, rellene todos los campos para agregar la tienda.</p></html>");

        lblInsertNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInsertNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInsertNombre.setLabelFor(txtInsertNombre);
        lblInsertNombre.setText("Nombre");
        lblInsertNombre.setMaximumSize(new java.awt.Dimension(147, 25));
        lblInsertNombre.setMinimumSize(new java.awt.Dimension(147, 25));
        lblInsertNombre.setPreferredSize(new java.awt.Dimension(147, 25));

        lblInsertLocalidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInsertLocalidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInsertLocalidad.setLabelFor(txtInsertLocalidad);
        lblInsertLocalidad.setText("Localidad");
        lblInsertLocalidad.setMaximumSize(new java.awt.Dimension(147, 25));
        lblInsertLocalidad.setMinimumSize(new java.awt.Dimension(147, 25));
        lblInsertLocalidad.setPreferredSize(new java.awt.Dimension(147, 25));

        lblInsertProvincia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInsertProvincia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInsertProvincia.setLabelFor(cmbInsertProvincia);
        lblInsertProvincia.setText("Provincia");
        lblInsertProvincia.setMaximumSize(new java.awt.Dimension(147, 25));
        lblInsertProvincia.setMinimumSize(new java.awt.Dimension(147, 25));
        lblInsertProvincia.setPreferredSize(new java.awt.Dimension(147, 25));

        lblInsertCodPost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInsertCodPost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInsertCodPost.setLabelFor(txtInsertCodPost);
        lblInsertCodPost.setText("Código postal");
        lblInsertCodPost.setFocusable(false);
        lblInsertCodPost.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblInsertCodPost.setMaximumSize(new java.awt.Dimension(147, 25));
        lblInsertCodPost.setMinimumSize(new java.awt.Dimension(147, 25));
        lblInsertCodPost.setPreferredSize(new java.awt.Dimension(147, 25));

        lblInsertSuperficie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInsertSuperficie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInsertSuperficie.setLabelFor(txtInsertSuperficie);
        lblInsertSuperficie.setText("Superficie");
        lblInsertSuperficie.setMaximumSize(new java.awt.Dimension(147, 25));
        lblInsertSuperficie.setMinimumSize(new java.awt.Dimension(147, 25));
        lblInsertSuperficie.setPreferredSize(new java.awt.Dimension(147, 25));

        lblInsertFechApertura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInsertFechApertura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInsertFechApertura.setLabelFor(spnInsertFechApertura);
        lblInsertFechApertura.setText("Fecha de apertura");
        lblInsertFechApertura.setMinimumSize(new java.awt.Dimension(147, 25));

        txtInsertNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInsertNombre.setMaximumSize(new java.awt.Dimension(400, 30));
        txtInsertNombre.setMinimumSize(new java.awt.Dimension(400, 30));
        txtInsertNombre.setPreferredSize(new java.awt.Dimension(400, 30));

        txtInsertLocalidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInsertLocalidad.setMaximumSize(new java.awt.Dimension(400, 30));
        txtInsertLocalidad.setMinimumSize(new java.awt.Dimension(400, 30));
        txtInsertLocalidad.setPreferredSize(new java.awt.Dimension(400, 30));

        cmbInsertProvincia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbInsertProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almería", "Cádiz", "Córdoba", "Granada", "Huelva", "Jaén", "Málaga", "Sevilla" }));
        cmbInsertProvincia.setMaximumSize(new java.awt.Dimension(400, 25));
        cmbInsertProvincia.setMinimumSize(new java.awt.Dimension(400, 25));
        cmbInsertProvincia.setPreferredSize(new java.awt.Dimension(400, 25));

        txtInsertCodPost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInsertCodPost.setMaximumSize(new java.awt.Dimension(400, 30));
        txtInsertCodPost.setMinimumSize(new java.awt.Dimension(400, 30));
        txtInsertCodPost.setPreferredSize(new java.awt.Dimension(400, 30));

        txtInsertSuperficie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInsertSuperficie.setMaximumSize(new java.awt.Dimension(400, 30));
        txtInsertSuperficie.setMinimumSize(new java.awt.Dimension(400, 30));
        txtInsertSuperficie.setPreferredSize(new java.awt.Dimension(400, 30));

        spnInsertFechApertura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnInsertFechApertura.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(970351200000L), null, java.util.Calendar.DAY_OF_MONTH));
        spnInsertFechApertura.setMaximumSize(new java.awt.Dimension(400, 30));
        spnInsertFechApertura.setMinimumSize(new java.awt.Dimension(400, 30));
        spnInsertFechApertura.setPreferredSize(new java.awt.Dimension(400, 30));

        btnInsertBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wipe.png"))); // NOI18N
        btnInsertBorrar.setToolTipText("Limpiar");
        btnInsertBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertBorrarActionPerformed(evt);
            }
        });

        btnInsertGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnInsertGuardar.setToolTipText("Añadir");
        btnInsertGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInsertCentroLayout = new javax.swing.GroupLayout(pnlInsertCentro);
        pnlInsertCentro.setLayout(pnlInsertCentroLayout);
        pnlInsertCentroLayout.setHorizontalGroup(
            pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertCentroLayout.createSequentialGroup()
                .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInsertCentroLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblInsertIndicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInsertTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlInsertCentroLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlInsertCentroLayout.createSequentialGroup()
                                        .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblInsertNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblInsertLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblInsertProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInsertNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtInsertLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addGroup(pnlInsertCentroLayout.createSequentialGroup()
                                                .addComponent(cmbInsertProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(pnlInsertCentroLayout.createSequentialGroup()
                                        .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblInsertSuperficie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblInsertFechApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblInsertCodPost, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnInsertFechApertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtInsertSuperficie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtInsertCodPost, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(pnlInsertCentroLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnInsertBorrar)
                        .addGap(155, 155, 155)
                        .addComponent(btnInsertGuardar)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlInsertCentroLayout.setVerticalGroup(
            pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertCentroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblInsertTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInsertIndicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsertNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInsertNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInsertLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInsertLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsertProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbInsertProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInsertCodPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInsertCodPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInsertSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInsertSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsertFechApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnInsertFechApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnlInsertCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInsertBorrar)
                    .addComponent(btnInsertGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInsert.add(pnlInsertCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInsert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertBorrarActionPerformed
        this.borraFormulario();
    }//GEN-LAST:event_btnInsertBorrarActionPerformed

    private void btnInsertGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertGuardarActionPerformed
        this.controlador.addTienda(this.txtInsertNombre.getText(), this.txtInsertLocalidad.getText(), (String)this.cmbInsertProvincia.getSelectedItem(), this.txtInsertCodPost.getText(), Double.parseDouble(this.txtInsertSuperficie.getText()), (Date)this.spnInsertFechApertura.getValue());
        this.borraFormulario();
        this.padre.recarga();
        dispose();
    }//GEN-LAST:event_btnInsertGuardarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int escoger=JOptionPane.showConfirmDialog(this, "¿Desea cerrar la ventana? Si la cierra, perderá toda la información", "Cerrar",JOptionPane.YES_NO_OPTION);
        if(escoger==JOptionPane.YES_OPTION){
            this.borraFormulario();
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
        else{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void borraFormulario(){
        this.txtInsertNombre.setText("");
        this.txtInsertLocalidad.setText("");
        this.txtInsertCodPost.setText("");
        this.txtInsertSuperficie.setText("");
        this.cmbInsertProvincia.setSelectedIndex(0);
        this.spnInsertFechApertura.setValue(new Date());
    }
    
    private Controlador controlador;
    private DialogTiendas padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertBorrar;
    private javax.swing.JButton btnInsertGuardar;
    private javax.swing.JComboBox<String> cmbInsertProvincia;
    private javax.swing.JLabel lblInsertCodPost;
    private javax.swing.JLabel lblInsertFechApertura;
    private javax.swing.JLabel lblInsertIndicaciones;
    private javax.swing.JLabel lblInsertLocalidad;
    private javax.swing.JLabel lblInsertNombre;
    private javax.swing.JLabel lblInsertProvincia;
    private javax.swing.JLabel lblInsertSuperficie;
    private javax.swing.JLabel lblInsertTitulo;
    private javax.swing.JPanel pnlInsert;
    private javax.swing.JPanel pnlInsertCentro;
    private javax.swing.JPanel pnlInsertDcha;
    private javax.swing.JPanel pnlInsertIzqda;
    private javax.swing.JSpinner spnInsertFechApertura;
    private javax.swing.JTextField txtInsertCodPost;
    private javax.swing.JTextField txtInsertLocalidad;
    private javax.swing.JTextField txtInsertNombre;
    private javax.swing.JTextField txtInsertSuperficie;
    // End of variables declaration//GEN-END:variables
}
