/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import controlador.Controlador;
import controlador.ModeloTiendas;
import javax.swing.table.TableModel;

/**
 *
 * @author violi
 */
public class DialogTiendas extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public DialogTiendas(java.awt.Frame parent, boolean modal, Controlador ctrl) {
        super(parent, modal);
        this.padre=(FrameLogin)parent;
        this.controlador=ctrl;
        initComponents();
        this.lblTiendasUsuario.setText("Usted está logueado como: "+this.controlador.getUsuarioLogeado()+".   ");
        this.tblTiendas.setModel(new ModeloTiendas(this.controlador.getListaTiendas()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optPanAcercaDe = new javax.swing.JOptionPane();
        pnlLista = new javax.swing.JPanel();
        pnlListaDcha = new javax.swing.JPanel();
        pnlListaIzqda = new javax.swing.JPanel();
        panelListaCtro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiendas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblTiendasTitulo = new javax.swing.JLabel();
        lblTiendasUsuario = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuInsertar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();
        menuBorrar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlLista.setLayout(new java.awt.BorderLayout());

        pnlListaDcha.setBackground(new java.awt.Color(0, 153, 51));
        pnlListaDcha.setPreferredSize(new java.awt.Dimension(50, 300));

        javax.swing.GroupLayout pnlListaDchaLayout = new javax.swing.GroupLayout(pnlListaDcha);
        pnlListaDcha.setLayout(pnlListaDchaLayout);
        pnlListaDchaLayout.setHorizontalGroup(
            pnlListaDchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlListaDchaLayout.setVerticalGroup(
            pnlListaDchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        pnlLista.add(pnlListaDcha, java.awt.BorderLayout.EAST);

        pnlListaIzqda.setBackground(new java.awt.Color(255, 255, 204));
        pnlListaIzqda.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout pnlListaIzqdaLayout = new javax.swing.GroupLayout(pnlListaIzqda);
        pnlListaIzqda.setLayout(pnlListaIzqdaLayout);
        pnlListaIzqdaLayout.setHorizontalGroup(
            pnlListaIzqdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlListaIzqdaLayout.setVerticalGroup(
            pnlListaIzqdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        pnlLista.add(pnlListaIzqda, java.awt.BorderLayout.WEST);

        panelListaCtro.setLayout(new java.awt.BorderLayout());

        tblTiendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblTiendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTiendas.setRowHeight(30);
        jScrollPane1.setViewportView(tblTiendas);

        panelListaCtro.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTiendasTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTiendasTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTiendasTitulo.setText("Tiendas");

        lblTiendasUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTiendasUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTiendasUsuario.setText("Usuario");
        lblTiendasUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTiendasTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTiendasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTiendasTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
            .addComponent(lblTiendasUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelListaCtro.add(jPanel1, java.awt.BorderLayout.NORTH);

        pnlLista.add(panelListaCtro, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuInsertar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuInsertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuInsertar.setText("<html><u>I</u>nsertar</html>");
        menuInsertar.setHideActionText(true);
        menuInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInsertarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuInsertar);

        menuEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuEditar.setText("Editar");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuEditar);

        menuBorrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuBorrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuBorrar.setText("Borrar");
        menuBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBorrarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuBorrar);

        menuPrincipal.add(menuArchivo);

        menuAyuda.setText("Ayuda");
        menuAyuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuAcercaDe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuAcercaDe.setText("Acerca de...");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(menuAcercaDe);

        menuPrincipal.add(menuAyuda);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int escoger=JOptionPane.showConfirmDialog(this, "¿Desea cerrar la sesión?", "Sesión",JOptionPane.YES_NO_OPTION);
        if(escoger==JOptionPane.YES_OPTION){
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.padre.reiniciar();
        }
        else{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void menuInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInsertarActionPerformed
        this.dInsercion=new DialogInsercion(this, true, this.controlador);
        this.dInsercion.setVisible(true);
        
    }//GEN-LAST:event_menuInsertarActionPerformed

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        JOptionPane.showMessageDialog(this, "Aplicación multipropósito", "Acerca de...",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void menuBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBorrarActionPerformed
        int tiendaSeleccionada=this.tblTiendas.getSelectedRow();
        if (tiendaSeleccionada==-1){
                JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna tienda.");
        }
        else{
            if(JOptionPane.showConfirmDialog(this, "Se va a eliminar la tienda \""+this.tblTiendas.getValueAt(tiendaSeleccionada, 1)+"\", ¿Está seguro?", "Borrar", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                this.controlador.deleteTienda(tiendaSeleccionada);
                this.recarga();
                JOptionPane.showMessageDialog(this, "Se ha borrado la tienda.");
            }
        }
    }//GEN-LAST:event_menuBorrarActionPerformed

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        int tiendaSeleccionada=this.tblTiendas.getSelectedRow();
        if (tiendaSeleccionada==-1){
                JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna tienda.");
        }
        else{
            this.dEdicion=new DialogEdicion(this, true, this.controlador, tiendaSeleccionada);
            this.dEdicion.setVisible(true);
        }
    }//GEN-LAST:event_menuEditarActionPerformed
    
    protected void recarga(){
        ModeloTiendas m=(ModeloTiendas)this.tblTiendas.getModel();
        m.fireTableDataChanged();
    }
    
    private Controlador controlador;
    private FrameLogin padre;
    private DialogInsercion dInsercion;
    private DialogEdicion dEdicion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTiendasTitulo;
    private javax.swing.JLabel lblTiendasUsuario;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuBorrar;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuInsertar;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JOptionPane optPanAcercaDe;
    private javax.swing.JPanel panelListaCtro;
    private javax.swing.JPanel pnlLista;
    private javax.swing.JPanel pnlListaDcha;
    private javax.swing.JPanel pnlListaIzqda;
    private javax.swing.JTable tblTiendas;
    // End of variables declaration//GEN-END:variables
}
