/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import java.util.Date;
import controlador.Controlador;
import java.text.ParseException;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author violi
 */
public class DialogEdicion extends javax.swing.JDialog {

    /**
     * 
     * @param parent
     * @param modal
     * @param controlador 
     * @param seleccionada 
     */
    public DialogEdicion(DialogTiendas parent, boolean modal, Controlador controlador, int seleccionada) {
        super(parent, modal);
        initComponents();
        this.controlador=controlador;
        this.tiendaSeleccionada=seleccionada;
        this.padre=parent;
        recuperaFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEdit = new javax.swing.JPanel();
        pnlEditDcha = new javax.swing.JPanel();
        pnlEditIzqda = new javax.swing.JPanel();
        pnlEditCentro = new javax.swing.JPanel();
        lblEditCodigo = new javax.swing.JLabel();
        lblEditTitulo = new javax.swing.JLabel();
        lblEditIndicaciones = new javax.swing.JLabel();
        lblEditNombre = new javax.swing.JLabel();
        lblEditLocalidad = new javax.swing.JLabel();
        lblEditProvincia = new javax.swing.JLabel();
        lblEditCodPost = new javax.swing.JLabel();
        lblEditSuperficie = new javax.swing.JLabel();
        lblEditFechApertura = new javax.swing.JLabel();
        txtEditCodigo = new javax.swing.JTextField();
        txtEditNombre = new javax.swing.JTextField();
        txtEditLocalidad = new javax.swing.JTextField();
        cmbEditProvincia = new javax.swing.JComboBox<>();
        txtEditCodPost = new javax.swing.JTextField();
        txtEditSuperficie = new javax.swing.JTextField();
        spnEditFechApertura = new javax.swing.JSpinner();
        btnEditAtras = new javax.swing.JButton();
        btnEditGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlEdit.setLayout(new java.awt.BorderLayout());

        pnlEditDcha.setBackground(new java.awt.Color(0, 153, 51));
        pnlEditDcha.setPreferredSize(new java.awt.Dimension(50, 300));

        javax.swing.GroupLayout pnlEditDchaLayout = new javax.swing.GroupLayout(pnlEditDcha);
        pnlEditDcha.setLayout(pnlEditDchaLayout);
        pnlEditDchaLayout.setHorizontalGroup(
            pnlEditDchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlEditDchaLayout.setVerticalGroup(
            pnlEditDchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        pnlEdit.add(pnlEditDcha, java.awt.BorderLayout.EAST);

        pnlEditIzqda.setBackground(new java.awt.Color(255, 255, 204));
        pnlEditIzqda.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout pnlEditIzqdaLayout = new javax.swing.GroupLayout(pnlEditIzqda);
        pnlEditIzqda.setLayout(pnlEditIzqdaLayout);
        pnlEditIzqdaLayout.setHorizontalGroup(
            pnlEditIzqdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlEditIzqdaLayout.setVerticalGroup(
            pnlEditIzqdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlEdit.add(pnlEditIzqda, java.awt.BorderLayout.WEST);

        pnlEditCentro.setBackground(new java.awt.Color(255, 255, 255));

        lblEditCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEditCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditCodigo.setLabelFor(lblEditCodigo);
        lblEditCodigo.setText("Código");

        lblEditTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEditTitulo.setText("Editar Tienda");

        lblEditIndicaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEditIndicaciones.setText("<html><p>Por favor, modifique los campos que considere necesarios en la tienda.</p></html>");

        lblEditNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEditNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditNombre.setLabelFor(txtEditNombre);
        lblEditNombre.setText("Nombre");
        lblEditNombre.setMaximumSize(new java.awt.Dimension(147, 25));
        lblEditNombre.setMinimumSize(new java.awt.Dimension(147, 25));
        lblEditNombre.setPreferredSize(new java.awt.Dimension(147, 25));

        lblEditLocalidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEditLocalidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditLocalidad.setLabelFor(txtEditLocalidad);
        lblEditLocalidad.setText("Localidad");
        lblEditLocalidad.setMaximumSize(new java.awt.Dimension(147, 25));
        lblEditLocalidad.setMinimumSize(new java.awt.Dimension(147, 25));
        lblEditLocalidad.setPreferredSize(new java.awt.Dimension(147, 25));

        lblEditProvincia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEditProvincia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditProvincia.setLabelFor(cmbEditProvincia);
        lblEditProvincia.setText("Provincia");
        lblEditProvincia.setMaximumSize(new java.awt.Dimension(147, 25));
        lblEditProvincia.setMinimumSize(new java.awt.Dimension(147, 25));
        lblEditProvincia.setPreferredSize(new java.awt.Dimension(147, 25));

        lblEditCodPost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEditCodPost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditCodPost.setLabelFor(txtEditCodPost);
        lblEditCodPost.setText("Código postal");
        lblEditCodPost.setFocusable(false);
        lblEditCodPost.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblEditCodPost.setMaximumSize(new java.awt.Dimension(147, 25));
        lblEditCodPost.setMinimumSize(new java.awt.Dimension(147, 25));
        lblEditCodPost.setPreferredSize(new java.awt.Dimension(147, 25));

        lblEditSuperficie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEditSuperficie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditSuperficie.setLabelFor(txtEditSuperficie);
        lblEditSuperficie.setText("Superficie");
        lblEditSuperficie.setMaximumSize(new java.awt.Dimension(147, 25));
        lblEditSuperficie.setMinimumSize(new java.awt.Dimension(147, 25));
        lblEditSuperficie.setPreferredSize(new java.awt.Dimension(147, 25));

        lblEditFechApertura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEditFechApertura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditFechApertura.setLabelFor(spnEditFechApertura);
        lblEditFechApertura.setText("Fecha de apertura");
        lblEditFechApertura.setMinimumSize(new java.awt.Dimension(147, 25));

        txtEditCodigo.setEditable(false);
        txtEditCodigo.setMaximumSize(new java.awt.Dimension(400, 30));
        txtEditCodigo.setMinimumSize(new java.awt.Dimension(400, 30));
        txtEditCodigo.setPreferredSize(new java.awt.Dimension(400, 30));

        txtEditNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditNombre.setMaximumSize(new java.awt.Dimension(400, 30));
        txtEditNombre.setMinimumSize(new java.awt.Dimension(400, 30));
        txtEditNombre.setPreferredSize(new java.awt.Dimension(400, 30));

        txtEditLocalidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditLocalidad.setMaximumSize(new java.awt.Dimension(400, 30));
        txtEditLocalidad.setMinimumSize(new java.awt.Dimension(400, 30));
        txtEditLocalidad.setPreferredSize(new java.awt.Dimension(400, 30));

        cmbEditProvincia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEditProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almería", "Cádiz", "Córdoba", "Granada", "Huelva", "Jaén", "Málaga", "Sevilla" }));
        cmbEditProvincia.setMaximumSize(new java.awt.Dimension(400, 25));
        cmbEditProvincia.setMinimumSize(new java.awt.Dimension(400, 25));
        cmbEditProvincia.setPreferredSize(new java.awt.Dimension(400, 25));

        txtEditCodPost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditCodPost.setMaximumSize(new java.awt.Dimension(400, 30));
        txtEditCodPost.setMinimumSize(new java.awt.Dimension(400, 30));
        txtEditCodPost.setPreferredSize(new java.awt.Dimension(400, 30));

        txtEditSuperficie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditSuperficie.setMaximumSize(new java.awt.Dimension(400, 30));
        txtEditSuperficie.setMinimumSize(new java.awt.Dimension(400, 30));
        txtEditSuperficie.setPreferredSize(new java.awt.Dimension(400, 30));

        spnEditFechApertura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnEditFechApertura.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(970351200000L), null, java.util.Calendar.DAY_OF_MONTH));
        spnEditFechApertura.setEnabled(false);
        spnEditFechApertura.setMaximumSize(new java.awt.Dimension(400, 30));
        spnEditFechApertura.setMinimumSize(new java.awt.Dimension(400, 30));
        spnEditFechApertura.setPreferredSize(new java.awt.Dimension(400, 30));

        btnEditAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/previous.png"))); // NOI18N
        btnEditAtras.setToolTipText("Recargar datos originales");
        btnEditAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAtrasActionPerformed(evt);
            }
        });

        btnEditGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnEditGuardar.setToolTipText("Modificar tienda");
        btnEditGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditCentroLayout = new javax.swing.GroupLayout(pnlEditCentro);
        pnlEditCentro.setLayout(pnlEditCentroLayout);
        pnlEditCentroLayout.setHorizontalGroup(
            pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditCentroLayout.createSequentialGroup()
                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditCentroLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEditIndicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEditCentroLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlEditCentroLayout.createSequentialGroup()
                                        .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblEditNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblEditLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblEditCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(lblEditProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEditNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEditLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addGroup(pnlEditCentroLayout.createSequentialGroup()
                                                .addComponent(cmbEditProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtEditCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(pnlEditCentroLayout.createSequentialGroup()
                                        .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblEditSuperficie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblEditFechApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblEditCodPost, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnEditFechApertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEditSuperficie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEditCodPost, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(pnlEditCentroLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnEditAtras)
                        .addGap(155, 155, 155)
                        .addComponent(btnEditGuardar)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlEditCentroLayout.setVerticalGroup(
            pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditCentroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblEditTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditIndicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditCodigo)
                    .addComponent(txtEditCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEditLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEditProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEditCodPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditCodPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEditSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditFechApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnEditFechApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnlEditCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditAtras)
                    .addComponent(btnEditGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEdit.add(pnlEditCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAtrasActionPerformed
        this.recuperaFormulario();
    }//GEN-LAST:event_btnEditAtrasActionPerformed

    private void btnEditGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGuardarActionPerformed
        this.controlador.editTienda(this.tiendaSeleccionada, this.txtEditNombre.getText(), this.txtEditLocalidad.getText(), (String)this.cmbEditProvincia.getSelectedItem(), this.txtEditCodPost.getText(), Double.parseDouble(this.txtEditSuperficie.getText()));
        this.borraFormulario();
        this.padre.recarga();
        dispose();
    }//GEN-LAST:event_btnEditGuardarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int escoger=JOptionPane.showConfirmDialog(this, "¿Desea cerrar la ventana? Si la cierra, perderá todos los cambios", "Cerrar",JOptionPane.YES_NO_OPTION);
        if(escoger==JOptionPane.YES_OPTION){
            this.borraFormulario();
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
        else{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void recuperaFormulario(){
        this.txtEditCodigo.setText(this.controlador.getListaTiendas().get(tiendaSeleccionada).getCodigo());
        this.txtEditNombre.setText(this.controlador.getListaTiendas().get(tiendaSeleccionada).getNombre());
        this.txtEditLocalidad.setText(this.controlador.getListaTiendas().get(tiendaSeleccionada).getLocalidad());
        this.txtEditCodPost.setText(this.controlador.getListaTiendas().get(tiendaSeleccionada).getCodPostal());
        this.txtEditSuperficie.setText(String.valueOf(this.controlador.getListaTiendas().get(tiendaSeleccionada).getSuperficie()));
        this.cmbEditProvincia.setSelectedItem(this.controlador.getListaTiendas().get(tiendaSeleccionada).getProvincia());
        this.spnEditFechApertura.setValue(this.controlador.getListaTiendas().get(tiendaSeleccionada).getFechaApertura());
    }
    
    private void borraFormulario(){
        this.txtEditCodigo.setText("");
        this.txtEditNombre.setText("");
        this.txtEditLocalidad.setText("");
        this.txtEditCodPost.setText("");
        this.txtEditSuperficie.setText("");
        this.cmbEditProvincia.setSelectedIndex(0);
        this.spnEditFechApertura.setValue(new Date());
    }
    
    private Controlador controlador;
    private DialogTiendas padre;
    private int tiendaSeleccionada;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditAtras;
    private javax.swing.JButton btnEditGuardar;
    private javax.swing.JComboBox<String> cmbEditProvincia;
    private javax.swing.JLabel lblEditCodPost;
    private javax.swing.JLabel lblEditCodigo;
    private javax.swing.JLabel lblEditFechApertura;
    private javax.swing.JLabel lblEditIndicaciones;
    private javax.swing.JLabel lblEditLocalidad;
    private javax.swing.JLabel lblEditNombre;
    private javax.swing.JLabel lblEditProvincia;
    private javax.swing.JLabel lblEditSuperficie;
    private javax.swing.JLabel lblEditTitulo;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JPanel pnlEditCentro;
    private javax.swing.JPanel pnlEditDcha;
    private javax.swing.JPanel pnlEditIzqda;
    private javax.swing.JSpinner spnEditFechApertura;
    private javax.swing.JTextField txtEditCodPost;
    private javax.swing.JTextField txtEditCodigo;
    private javax.swing.JTextField txtEditLocalidad;
    private javax.swing.JTextField txtEditNombre;
    private javax.swing.JTextField txtEditSuperficie;
    // End of variables declaration//GEN-END:variables
}
