/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import controlador.Controlador;

/**
 *
 * @author violi
 */
public class FrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrameLogin() {
        this.controlador=new Controlador();
        initComponents();
        this.setIconImage(new ImageIcon(this.getClass().getResource("../img/automobile.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelLogin = new javax.swing.JPanel();
        panelDcha = new javax.swing.JPanel();
        panelIzq = new javax.swing.JPanel();
        panelHoriz = new javax.swing.JPanel();
        panelDchaCentro = new javax.swing.JPanel();
        panelIzqdaCentro = new javax.swing.JPanel();
        panelAbajo = new javax.swing.JPanel();
        panelCtro = new javax.swing.JPanel();
        lblUsu = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        panelArriba = new javax.swing.JPanel();
        panelEncimaInstrucciones = new javax.swing.JPanel();
        lblInstrucciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(402, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setPreferredSize(new java.awt.Dimension(402, 100));
        panelLogin.setLayout(new java.awt.BorderLayout());

        panelDcha.setBackground(new java.awt.Color(255, 255, 204));
        panelDcha.setMinimumSize(new java.awt.Dimension(50, 0));
        panelDcha.setPreferredSize(new java.awt.Dimension(50, 290));

        javax.swing.GroupLayout panelDchaLayout = new javax.swing.GroupLayout(panelDcha);
        panelDcha.setLayout(panelDchaLayout);
        panelDchaLayout.setHorizontalGroup(
            panelDchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelDchaLayout.setVerticalGroup(
            panelDchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        panelLogin.add(panelDcha, java.awt.BorderLayout.WEST);

        panelIzq.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout panelIzqLayout = new javax.swing.GroupLayout(panelIzq);
        panelIzq.setLayout(panelIzqLayout);
        panelIzqLayout.setHorizontalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelIzqLayout.setVerticalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelLogin.add(panelIzq, java.awt.BorderLayout.EAST);

        panelHoriz.setLayout(new java.awt.BorderLayout());

        panelDchaCentro.setBackground(new java.awt.Color(255, 255, 255));
        panelDchaCentro.setMaximumSize(new java.awt.Dimension(10, 32767));
        panelDchaCentro.setMinimumSize(new java.awt.Dimension(10, 0));
        panelDchaCentro.setPreferredSize(new java.awt.Dimension(10, 0));

        javax.swing.GroupLayout panelDchaCentroLayout = new javax.swing.GroupLayout(panelDchaCentro);
        panelDchaCentro.setLayout(panelDchaCentroLayout);
        panelDchaCentroLayout.setHorizontalGroup(
            panelDchaCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDchaCentroLayout.setVerticalGroup(
            panelDchaCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelHoriz.add(panelDchaCentro, java.awt.BorderLayout.EAST);

        panelIzqdaCentro.setBackground(new java.awt.Color(255, 255, 255));
        panelIzqdaCentro.setMaximumSize(new java.awt.Dimension(10, 32767));
        panelIzqdaCentro.setMinimumSize(new java.awt.Dimension(10, 0));
        panelIzqdaCentro.setPreferredSize(new java.awt.Dimension(10, 150));

        javax.swing.GroupLayout panelIzqdaCentroLayout = new javax.swing.GroupLayout(panelIzqdaCentro);
        panelIzqdaCentro.setLayout(panelIzqdaCentroLayout);
        panelIzqdaCentroLayout.setHorizontalGroup(
            panelIzqdaCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelIzqdaCentroLayout.setVerticalGroup(
            panelIzqdaCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panelHoriz.add(panelIzqdaCentro, java.awt.BorderLayout.WEST);

        panelAbajo.setBackground(new java.awt.Color(255, 255, 255));
        panelAbajo.setMinimumSize(new java.awt.Dimension(0, 50));
        panelAbajo.setPreferredSize(new java.awt.Dimension(0, 50));

        javax.swing.GroupLayout panelAbajoLayout = new javax.swing.GroupLayout(panelAbajo);
        panelAbajo.setLayout(panelAbajoLayout);
        panelAbajoLayout.setHorizontalGroup(
            panelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAbajoLayout.setVerticalGroup(
            panelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelHoriz.add(panelAbajo, java.awt.BorderLayout.SOUTH);

        panelCtro.setBackground(new java.awt.Color(255, 255, 255));
        panelCtro.setAutoscrolls(true);
        panelCtro.setMinimumSize(new java.awt.Dimension(151, 150));
        panelCtro.setPreferredSize(new java.awt.Dimension(286, 286));
        java.awt.GridBagLayout panelCtroLayout = new java.awt.GridBagLayout();
        panelCtroLayout.columnWidths = new int[] {2};
        panelCtroLayout.rowHeights = new int[] {2};
        panelCtro.setLayout(panelCtroLayout);

        lblUsu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsu.setLabelFor(txtUsu);
        lblUsu.setText("Usuario");
        lblUsu.setFocusable(false);
        lblUsu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCtro.add(lblUsu, gridBagConstraints);

        txtUsu.setToolTipText("Introduca tu nombre de usuario");
        txtUsu.setMaximumSize(new java.awt.Dimension(130, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCtro.add(txtUsu, gridBagConstraints);

        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPass.setLabelFor(txtPass);
        lblPass.setText("Contraseña");
        lblPass.setFocusable(false);
        lblPass.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCtro.add(lblPass, gridBagConstraints);

        txtPass.setMaximumSize(new java.awt.Dimension(130, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCtro.add(txtPass, gridBagConstraints);

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCtro.add(btnEntrar, gridBagConstraints);

        panelHoriz.add(panelCtro, java.awt.BorderLayout.CENTER);

        panelArriba.setBackground(new java.awt.Color(255, 255, 255));
        panelArriba.setMinimumSize(new java.awt.Dimension(100, 90));
        panelArriba.setPreferredSize(new java.awt.Dimension(100, 90));
        panelArriba.setLayout(new java.awt.BorderLayout());

        panelEncimaInstrucciones.setBackground(new java.awt.Color(255, 255, 255));
        panelEncimaInstrucciones.setMinimumSize(new java.awt.Dimension(100, 50));
        panelEncimaInstrucciones.setPreferredSize(new java.awt.Dimension(302, 50));

        javax.swing.GroupLayout panelEncimaInstruccionesLayout = new javax.swing.GroupLayout(panelEncimaInstrucciones);
        panelEncimaInstrucciones.setLayout(panelEncimaInstruccionesLayout);
        panelEncimaInstruccionesLayout.setHorizontalGroup(
            panelEncimaInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        panelEncimaInstruccionesLayout.setVerticalGroup(
            panelEncimaInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelArriba.add(panelEncimaInstrucciones, java.awt.BorderLayout.CENTER);

        lblInstrucciones.setText("<html><p><b>Por favor, introduzca sus credenciales para entrar a la aplicación</b></p></html>");
        lblInstrucciones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblInstrucciones.setMinimumSize(new java.awt.Dimension(100, 40));
        lblInstrucciones.setPreferredSize(new java.awt.Dimension(339, 200));
        lblInstrucciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelArriba.add(lblInstrucciones, java.awt.BorderLayout.SOUTH);

        panelHoriz.add(panelArriba, java.awt.BorderLayout.NORTH);

        panelLogin.add(panelHoriz, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if(this.controlador.testUsuario(this.txtUsu.getText(),this.txtPass.getText())){
            this.setVisible(false);
            this.ventanaGestion=new DialogTiendas(this, true, this.controlador);
            this.ventanaGestion.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña no válidos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.txtUsu.setText("");
        this.txtPass.setText("");
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int escoger=JOptionPane.showConfirmDialog(this, "¿Está seguro de que quiere salir?", "Salir",JOptionPane.YES_NO_OPTION);
        if(escoger==JOptionPane.YES_OPTION){
           System.exit(0);
        }
        else{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    protected void reiniciar(){
        this.setVisible(true);
        this.controlador.cierraSesion();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }
    private Controlador controlador;
    private DialogTiendas ventanaGestion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUsu;
    private javax.swing.JPanel panelAbajo;
    private javax.swing.JPanel panelArriba;
    private javax.swing.JPanel panelCtro;
    private javax.swing.JPanel panelDcha;
    private javax.swing.JPanel panelDchaCentro;
    private javax.swing.JPanel panelEncimaInstrucciones;
    private javax.swing.JPanel panelHoriz;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JPanel panelIzqdaCentro;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
